# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Florian M. Hollenbach's Website
author :
  name : Florian M. Hollenbach
  email : fhollenbach@tamu.edu
  github : fhollenbach
  twitter : fhollenbach
  feedburner : nil

markdown: kramdown
theme: jekyll-theme-slate

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]


production_url : https://fhollenbach.github.io/

JB :
  version : 0.3.0