# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Florian M. Hollenbach's Website

author:
  name: Florian M. Hollenbach
  avatar: /img/images/portrait.png
  bio: Assistant Professor at Texas A&M University
  links:
    - label: Website
      icon: fas fa-fw fa-link
      url: https://fhollenbach.org
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/fhollenbach
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/fhollenbach


markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]


production_url : https://fhollenbach.github.io/

JB :
  version : 0.3.0