# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Florian M. Hollenbach's Website
author:
  name: Florian M. Hollenbach

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]


production_url : https://fhollenbach.github.io/

JB :
  version : 0.3.0