# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Florian M. Hollenbach"
title_separator          : "-"
name                     : "Florian M. Hollenbach"
description              : "Florian M. Hollenbach's Website."
url                      :  "https://fhollenbach.github.io"
baseurl                  : #"/index.html" # the subpath of your site, e.g. "/index"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"


google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :


# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)



# Site Author
author:
  name             : "Florian M. Hollenbach"
  avatar           : "/assets/img/portrait.png"
  bio              : "I am an assistant professor in political science at Texas A&M University"
  location         : "BCS, TX"
  email            :
  links:
   # - label: "Email"
    #  icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:fhollenbach@tamu.edu"
   # - label: "Website"
   #   icon: "fas fa-fw fa-link"
      # url: "https://fhollenbach.org"
   # - label: "Twitter"
   #   icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/fhollenbach"
   # - label: "GitHub"
    #  icon: "fab fa-fw fa-github"
      # url: "https://github.com/fhollenbach"
